# Generated by Django 5.0.1 on 2024-01-25 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('creation_date', models.DateField(verbose_name='Creation Date')),
                ('image', models.ImageField(upload_to='company_images/', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
                ('location', models.TextField(verbose_name='Location')),
                ('location_en', models.TextField(null=True, verbose_name='Location')),
                ('location_ar', models.TextField(null=True, verbose_name='Location')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram Link')),
                ('instagram', models.CharField(blank=True, max_length=20, verbose_name='Instagram')),
                ('viber', models.CharField(blank=True, max_length=20, verbose_name='Viber')),
                ('telegram', models.CharField(blank=True, max_length=20, verbose_name='Telegram')),
                ('map_embed_code', models.TextField(verbose_name='Map Embed Code')),
                ('industry', models.CharField(max_length=100, verbose_name='Industry')),
                ('industry_en', models.CharField(max_length=100, null=True, verbose_name='Industry')),
                ('industry_ar', models.CharField(max_length=100, null=True, verbose_name='Industry')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('country_en', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('country_ar', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.industrycategory', verbose_name='Category')),
                ('category_ar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.industrycategory', verbose_name='Category')),
                ('category_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.industrycategory', verbose_name='Category')),
            ],
        ),
    ]
