# Generated by Django 5.0.1 on 2024-01-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrycategory',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Image'),
        ),
    ]
