# Generated by Django 5.0.1 on 2024-01-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subcategory_company_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
